name: Build and deploy Node.js app to Azure Web App - Dynamic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create .env file from GitHub Secrets
        run: |
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build:ci

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D8D26D972E54AC8B24C0CD6E11E3954 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B2410AD1C424FC895791B020EF76882 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD42639F7B9543C2AA9E5274FA8EF493 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Dynamic'
          slot-name: 'Production'
          package: .
